---
- hosts: webservers
  remote_user: ubuntu
  tasks:
    - name: "Pull changes"
      ansible.builtin.git:
        repo: 'git@github.com:MadhavShroff/makeitaifor-me-server.git' # SSH URL
        dest: /home/ubuntu/makeitaifor-me-server
        key_file: /home/ubuntu/.ssh/id_rsa # Path to private key
        accept_hostkey: true
        force: yes
      become: yes

    - name: "Run redeploy script"
      ansible.builtin.command: '/bin/bash /home/ubuntu/makeitaifor-me-server/redeploy.sh'
      become: yes
      register: redeploy_result  # Register the output to a variable

    - name: "Print redeploy result"
      debug:
        msg: "{{ item }}"
      loop: "{{ redeploy_result.stdout_lines }}"
      when: redeploy_result.stdout_lines is defined  # Make sure stdout_lines exists before trying to print it